server:
  port: 0
spring:
  application:
    name: offers-complex-bus

  config:
    import:
    - optional:configserver:http://localhost:8888/
    
  rabbitmq:
    host: 192.168.100.13
    port: 5672
    username: admin
    password: admin
